### ISSUE TITLE
Add verbose option for readdir

### ISSUE THREAD

**Issue by tracker1** [tracker1/node-smb2#5]
https://github.com/petvek/node-smb2/commit/5d78722ac961e3be2116049eb3359ff175ce9299#diff-11651710b110333093286a81236615d9

https://github.com/petvek/node-smb2/commit/52e89cd85f2bac4fbcbb7b474397a01c3baa06f4#diff-11651710b110333093286a81236615d9

**Comment by tracker1** [comment]
@petvek What's your real name, so I can update the contributors list when I integrate your option for readdir?

**Comment by petvek** [comment]
Peter Verkoyen.
Thanks

2018-05-25 15:00 GMT+02:00 Michael J. Ryan <notifications@github.com>:

**Comment by tracker1** [comment]
@petvek thanks, added size to the readdir response, as well as refactoring the time conversion logic.  It's already returning a "verbose" object response, so didn't add the specific option, but it was helpful.
